#!/bin/bash

_erlch() {
    local cur=${COMP_WORDS[COMP_CWORD]}
    COMPREPLY=( $(compgen -W "help install list use" -- $cur) )

    if [[ $COMP_CWORD -eq 2 ]] ; then
        case ${COMP_WORDS[1]} in
            use|uninstall)
                local versions=`ls $HOME/.erlch/versions`
                COMPREPLY=( $(compgen -W "$versions" -- $cur) )
                ;;
            rm-cache)
                local versions=`ls $HOME/.erlch/cache`
                COMPREPLY=( $(compgen -W "$versions" -- $cur) )
                ;;
            install|download)
                if [[ -f "$HOME/.erlch/.version_list" ]] ; then
                    local versions=`ls $HOME/.erlch/.version_list`
                    COMPREPLY=( $(compgen -W "$versions" -- $cur) )
                fi
                ;;
            help)
                COMPREPLY=( $(compgen -W "download install list use fetch uninstall rm-cache" -- $cur) )
                ;;
        esac
    fi
}

complete -F _erlch erlch
